import json

# Sample JSON data
json_data = '''
{
    "status": true,
    "message": "Banks retrieved",
    "data": [
        {
            "id": 325,
            "name": "Absa Bank Kenya Plc",
            "slug": "absa-bank-kenya-plc-ke-usd",
            "code": "03",
            "longcode": "03",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 191,
            "name": "Absa Bank Kenya Plc",
            "slug": "absa-bank-kenya-plc-ke",
            "code": "03",
            "longcode": "03",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": "2022-03-01T21:11:16.000Z"
        },
        {
            "id": 340,
            "name": "Access Bank Kenya",
            "slug": "access-bank-kenya-ke-usd",
            "code": "26",
            "longcode": "26",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 208,
            "name": "Access Bank Kenya",
            "slug": "access-bank-kenya-ke",
            "code": "26",
            "longcode": "26",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": "2022-03-17T09:59:25.000Z"
        },
        {
            "id": 343,
            "name": "African BankingCorporation Ltd",
            "slug": "african-bankingcorporation-ltd-ke-usd",
            "code": "35",
            "longcode": "35",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 211,
            "name": "African BankingCorporation Ltd",
            "slug": "african-bankingcorporation-ltd-ke",
            "code": "35",
            "longcode": "35",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 337,
            "name": "Bank of Africa Kenya Ltd",
            "slug": "bank-of-africa-kenya-ltd-ke-usd",
            "code": "19",
            "longcode": "19",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 204,
            "name": "Bank of Africa Kenya Ltd",
            "slug": "bank-of-africa-kenya-ltd-ke",
            "code": "19",
            "longcode": "19",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 327,
            "name": "Bank of Baroda Kenya Limited",
            "slug": "bank-of-baroda-kenya-limited-ke-usd",
            "code": "06",
            "longcode": "06",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 193,
            "name": "Bank of Baroda Kenya Limited",
            "slug": "bank-of-baroda-kenya-limited-ke",
            "code": "06",
            "longcode": "06",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 326,
            "name": "Bank of India",
            "slug": "bank-of-india-ke-usd",
            "code": "05",
            "longcode": "05",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 192,
            "name": "Bank of India",
            "slug": "bank-of-india-ke",
            "code": "05",
            "longcode": "05",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 719,
            "name": "Caritas Microfinance Bank",
            "slug": "caritas-microfinance-bank-ke",
            "code": "48",
            "longcode": "48",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2023-10-13T12:19:55.000Z",
            "updatedAt": "2023-10-13T12:19:55.000Z"
        },
        {
            "id": 720,
            "name": "Caritas Microfinance Bank",
            "slug": "caritas-microfinance-bank-ke-usd",
            "code": "48",
            "longcode": "48",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2023-10-13T12:19:55.000Z",
            "updatedAt": "2023-10-13T12:19:55.000Z"
        },
        {
            "id": 330,
            "name": "Central Bank of Kenya",
            "slug": "central-bank-of-kenya-ke-usd",
            "code": "09",
            "longcode": "09",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 196,
            "name": "Central Bank of Kenya",
            "slug": "central-bank-of-kenya-ke",
            "code": "09",
            "longcode": "09",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 717,
            "name": "Choice Microfinance Bank",
            "slug": "choice-microfinance-bank-ke",
            "code": "36",
            "longcode": "36",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2023-10-13T12:19:55.000Z",
            "updatedAt": "2023-10-13T12:19:55.000Z"
        },
        {
            "id": 718,
            "name": "Choice Microfinance Bank",
            "slug": "choice-microfinance-bank-ke-usd",
            "code": "36",
            "longcode": "36",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2023-10-13T12:19:55.000Z",
            "updatedAt": "2023-10-13T12:19:55.000Z"
        },
        {
            "id": 335,
            "name": "Citibank NA ",
            "slug": "citibank-na-ke-usd",
            "code": "16",
            "longcode": "16",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 201,
            "name": "Citibank NA ",
            "slug": "citibank-na-ke",
            "code": "16",
            "longcode": "16",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 332,
            "name": "Co-operative Bank of Kenya Ltd",
            "slug": "co-operative-bank-of-kenya-ltd-ke-usd",
            "code": "11",
            "longcode": "11",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 198,
            "name": "Co-operative Bank of Kenya Ltd",
            "slug": "co-operative-bank-of-kenya-ltd-ke",
            "code": "11",
            "longcode": "11",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 338,
            "name": "Consolidated Bank of Kenya Ltd",
            "slug": "consolidated-bank-of-kenya-ltd-ke-usd",
            "code": "23",
            "longcode": "23",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 206,
            "name": "Consolidated Bank of Kenya Ltd",
            "slug": "consolidated-bank-of-kenya-ltd-ke",
            "code": "23",
            "longcode": "23",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 339,
            "name": "Credit Bank Limited",
            "slug": "credit-bank-limited-ke-usd",
            "code": "25",
            "longcode": "25",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 207,
            "name": "Credit Bank Limited",
            "slug": "credit-bank-limited-ke",
            "code": "25",
            "longcode": "25",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 352,
            "name": "Development Bank of Kenya Ltd",
            "slug": "development-bank-of-kenya-ltd-ke-usd",
            "code": "59",
            "longcode": "59",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 223,
            "name": "Development Bank of Kenya Ltd",
            "slug": "development-bank-of-kenya-ltd-ke",
            "code": "59",
            "longcode": "59",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 321,
            "name": "Diamond Trust Bank Ltd",
            "slug": "diamond-trust-bank-ltd-ke-usd",
            "code": "63",
            "longcode": "63",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-10T08:13:14.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 225,
            "name": "Diamond Trust Bank Ltd",
            "slug": "diamond-trust-bank-ltd-ke",
            "code": "63",
            "longcode": "63",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 288,
            "name": "Dubai Islamic Bank Ltd",
            "slug": "dubai-islamic-bank-ltd-ke",
            "code": "75",
            "longcode": "75",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-03-17T09:59:25.000Z",
            "updatedAt": null
        },
        {
            "id": 358,
            "name": "Dubai Islamic Bank Ltd",
            "slug": "dubai-islamic-bank-ltd-ke-usd",
            "code": "75",
            "longcode": "75",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 344,
            "name": "Ecobank Kenya Limited",
            "slug": "ecobank-kenya-limited-ke-usd",
            "code": "43",
            "longcode": "43",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 215,
            "name": "Ecobank Kenya Limited",
            "slug": "ecobank-kenya-limited-ke",
            "code": "43",
            "longcode": "43",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 354,
            "name": "Equity Bank ltd",
            "slug": "equity-bank-ltd-ke-usd",
            "code": "68",
            "longcode": "68",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 227,
            "name": "Equity Bank ltd",
            "slug": "equity-bank-ltd-ke",
            "code": "68",
            "longcode": "68",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 355,
            "name": "Family Bank Ltd",
            "slug": "family-bank-ltd-ke-usd",
            "code": "70",
            "longcode": "70",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 228,
            "name": "Family Bank Ltd",
            "slug": "family-bank-ltd-ke",
            "code": "70",
            "longcode": "70",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 292,
            "name": "Faulu Microfinance Bank",
            "slug": "faulu-microfinance-bank-ke",
            "code": "79",
            "longcode": "79",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-03-17T09:59:25.000Z",
            "updatedAt": null
        },
        {
            "id": 362,
            "name": "Faulu Microfinance Bank",
            "slug": "faulu-microfinance-bank-ke-usd",
            "code": "79",
            "longcode": "79",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 348,
            "name": "Guaranty Trust Bank Kenya",
            "slug": "guaranty-trust-bank-kenya-ke-usd",
            "code": "53",
            "longcode": "53",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 219,
            "name": "Guaranty Trust Bank Kenya",
            "slug": "guaranty-trust-bank-kenya-ke",
            "code": "53",
            "longcode": "53",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": "2022-03-17T09:59:25.000Z"
        },
        {
            "id": 350,
            "name": "Guardian Bank Ltd",
            "slug": "guardian-bank-ltd-ke-usd",
            "code": "55",
            "longcode": "55",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 221,
            "name": "Guardian Bank Ltd",
            "slug": "guardian-bank-ltd-ke",
            "code": "55",
            "longcode": "55",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 356,
            "name": "Gulf African Bank Ltd",
            "slug": "gulf-african-bank-ltd-ke-usd",
            "code": "72",
            "longcode": "72",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 229,
            "name": "Gulf African Bank Ltd",
            "slug": "gulf-african-bank-ltd-ke",
            "code": "72",
            "longcode": "72",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 329,
            "name": "Habib Bank Limited",
            "slug": "habib-bank-limited-ke-usd",
            "code": "08",
            "longcode": "08",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 195,
            "name": "Habib Bank Limited",
            "slug": "habib-bank-limited-ke",
            "code": "08",
            "longcode": "08",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 289,
            "name": "Housing Finance Corporation (HFC Bank)",
            "slug": "housing-finance-corporation-ke",
            "code": "61",
            "longcode": "61",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-03-17T09:59:25.000Z",
            "updatedAt": null
        },
        {
            "id": 359,
            "name": "Housing Finance Corporation (HFC Bank)",
            "slug": "housing-finance-corporation-ke-usd",
            "code": "61",
            "longcode": "61",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 351,
            "name": "I & M Bank Ltd",
            "slug": "i-m-bank-ltd-ke-usd",
            "code": "57",
            "longcode": "57",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 222,
            "name": "I & M Bank Ltd",
            "slug": "i-m-bank-ltd-ke",
            "code": "57",
            "longcode": "57",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 347,
            "name": "Jamii Bora Bank Ltd",
            "slug": "jamii-bora-bank-ltd-ke-usd",
            "code": "51",
            "longcode": "51",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 218,
            "name": "Jamii Bora Bank Ltd",
            "slug": "jamii-bora-bank-ltd-ke",
            "code": "51",
            "longcode": "51",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 323,
            "name": "Kenya Commercial Bank Limited",
            "slug": "kenya-commercial-bank-limited-ke-usd",
            "code": "01",
            "longcode": "01",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 189,
            "name": "Kenya Commercial Bank Limited",
            "slug": "kenya-commercial-bank-limited-ke",
            "code": "01",
            "longcode": "01",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 290,
            "name": "Kenya Women Microfinance Bank",
            "slug": "kenya-women-microfinance-bank-ke",
            "code": "78",
            "longcode": "78",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-03-17T09:59:25.000Z",
            "updatedAt": null
        },
        {
            "id": 360,
            "name": "Kenya Women Microfinance Bank",
            "slug": "kenya-women-microfinance-bank-ke-usd",
            "code": "78",
            "longcode": "78",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 721,
            "name": "Kingdom Bank",
            "slug": "kingdom-bank-ke",
            "code": "51",
            "longcode": "51",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2023-10-13T12:19:55.000Z",
            "updatedAt": "2023-10-13T12:19:55.000Z"
        },
        {
            "id": 722,
            "name": "Kingdom Bank",
            "slug": "kingdom-bank-ke-usd",
            "code": "51",
            "longcode": "51",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2023-10-13T12:19:55.000Z",
            "updatedAt": "2023-10-13T12:19:55.000Z"
        },
        {
            "id": 334,
            "name": "M-Oriental Bank Ltd",
            "slug": "m-oriental-bank-ltd-ke-usd",
            "code": "14",
            "longcode": "14",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 200,
            "name": "M-Oriental Bank Ltd",
            "slug": "m-oriental-bank-ltd-ke",
            "code": "14",
            "longcode": "14",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": "2022-03-17T09:59:25.000Z"
        },
     
        {
            "id": 291,
            "name": "Mayfair Bank",
            "slug": "mayfair-bank-ke",
            "code": "65",
            "longcode": "65",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-03-17T09:59:25.000Z",
            "updatedAt": null
        },
        {
            "id": 361,
            "name": "Mayfair Bank",
            "slug": "mayfair-bank-ke-usd",
            "code": "65",
            "longcode": "65",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 336,
            "name": "Middle East Bank Kenya Ltd",
            "slug": "middle-east-bank-kenya-ltd-ke-usd",
            "code": "18",
            "longcode": "18",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 203,
            "name": "Middle East Bank Kenya Ltd",
            "slug": "middle-east-bank-kenya-ltd-ke",
            "code": "18",
            "longcode": "18",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 333,
            "name": "National Bank of Kenya Ltd",
            "slug": "national-bank-of-kenya-ltd-ke-usd",
            "code": "12",
            "longcode": "12",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 199,
            "name": "National Bank of Kenya Ltd",
            "slug": "national-bank-of-kenya-ltd-ke",
            "code": "12",
            "longcode": "12",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 328,
            "name": "NCBA Bank Kenya",
            "slug": "ncba-bank-kenya-ke-usd",
            "code": "07",
            "longcode": "07",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 194,
            "name": "NCBA Bank Kenya",
            "slug": "ncba-bank-kenya-ke",
            "code": "07",
            "longcode": "07",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": "2022-03-17T09:59:25.000Z"
        },
        {
            "id": 346,
            "name": "Paramount Universal Bank Ltd",
            "slug": "paramount-universal-bank-ltd-ke-usd",
            "code": "50",
            "longcode": "50",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 217,
            "name": "Paramount Universal Bank Ltd",
            "slug": "paramount-universal-bank-ltd-ke",
            "code": "50",
            "longcode": "50",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 293,
            "name": "PostBank Kenya",
            "slug": "post-bank-kenya-ke",
            "code": "62",
            "longcode": "62",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-03-17T09:59:25.000Z",
            "updatedAt": null
        },
        {
            "id": 363,
            "name": "PostBank Kenya",
            "slug": "post-bank-kenya-ke-usd",
            "code": "62",
            "longcode": "62",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 294,
            "name": "Premier Bank Kenya",
            "slug": "premier-bank-ke",
            "code": "74",
            "longcode": "74",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-03-17T09:59:25.000Z",
            "updatedAt": "2023-10-13T12:19:55.000Z"
        },
        {
            "id": 364,
            "name": "Premier Bank Kenya",
            "slug": "premier-bank-ke-usd",
            "code": "74",
            "longcode": "74",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2023-10-13T12:19:55.000Z"
        },
        {
            "id": 331,
            "name": "Prime Bank Limited",
            "slug": "prime-bank-limited-ke-usd",
            "code": "10",
            "longcode": "10",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 197,
            "name": "Prime Bank Limited",
            "slug": "prime-bank-limited-ke",
            "code": "10",
            "longcode": "10",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 341,
            "name": "SBM Bank Kenya",
            "slug": "sbm-bank-kenya-ke-usd",
            "code": "30",
            "longcode": "30",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 209,
            "name": "SBM Bank Kenya",
            "slug": "sbm-bank-kenya-ke",
            "code": "30",
            "longcode": "30",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": "2022-03-17T09:59:25.000Z"
        },
        {
            "id": 353,
            "name": "Sidian Bank Kenya",
            "slug": "sidian-bank-kenya-ke-usd",
            "code": "66",
            "longcode": "66",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 226,
            "name": "Sidian Bank Kenya",
            "slug": "sidian-bank-kenya-ke",
            "code": "66",
            "longcode": "66",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": "2022-03-17T09:59:25.000Z"
        },
        {
            "id": 345,
            "name": "Spire Bank Kenya",
            "slug": "spire-bank-kenya-ke-usd",
            "code": "49",
            "longcode": "49",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 216,
            "name": "Spire Bank Kenya",
            "slug": "spire-bank-kenya-ke",
            "code": "49",
            "longcode": "49",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": "2022-03-17T09:59:25.000Z"
        },
        {
            "id": 342,
            "name": "Stanbic Bank Kenya Limited",
            "slug": "stanbic-bank-kenya-limited-ke-usd",
            "code": "31",
            "longcode": "31",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 210,
            "name": "Stanbic Bank Kenya Limited",
            "slug": "stanbic-bank-kenya-limited-ke",
            "code": "31",
            "longcode": "31",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": "2022-03-17T09:59:25.000Z"
        },
        {
            "id": 324,
            "name": "Standard Chartered Bank Kenya",
            "slug": "standard-chartered-bank-kenya-ke-usd",
            "code": "02",
            "longcode": "02",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 190,
            "name": "Standard Chartered Bank Kenya",
            "slug": "standard-chartered-bank-kenya-ke",
            "code": "02",
            "longcode": "02",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 723,
            "name": "Stima Sacco",
            "slug": "stima-sacco-ke",
            "code": "89",
            "longcode": "89",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2023-10-13T12:19:55.000Z",
            "updatedAt": "2023-10-13T12:19:55.000Z"
        },
        {
            "id": 724,
            "name": "Stima Sacco",
            "slug": "stima-sacco-ke-usd",
            "code": "89",
            "longcode": "89",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2023-10-13T12:19:55.000Z",
            "updatedAt": "2023-10-13T12:19:55.000Z"
        },
        {
            "id": 357,
            "name": "UBA Kenya Bank Ltd",
            "slug": "uba-kenya-bank-ltd-ke-usd",
            "code": "76",
            "longcode": "76",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 230,
            "name": "UBA Kenya Bank Ltd",
            "slug": "uba-kenya-bank-ltd-ke",
            "code": "76",
            "longcode": "76",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        },
        {
            "id": 349,
            "name": "Victoria Commercial Bank Ltd",
            "slug": "victoria-commercial-bank-ltd-ke-usd",
            "code": "54",
            "longcode": "54",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "USD",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2022-06-21T08:13:27.000Z",
            "updatedAt": "2022-06-21T08:13:27.000Z"
        },
        {
            "id": 220,
            "name": "Victoria Commercial Bank Ltd",
            "slug": "victoria-commercial-bank-ltd-ke",
            "code": "54",
            "longcode": "54",
            "gateway": null,
            "pay_with_bank": false,
            "supports_transfer": true,
            "active": true,
            "country": "Kenya",
            "currency": "KES",
            "type": "kepss",
            "is_deleted": false,
            "createdAt": "2021-10-18T16:02:32.000Z",
            "updatedAt": null
        }
    ]
}
'''

# Parse JSON data
data = json.loads(json_data)

# Extract name and code values
name_code_list = [{bank['name']: int(bank['code'])} for bank in data['data']]

# Format the result
formatted_output = []
for item in name_code_list:
    bank_name, bank_code = list(item.items())[0]
    formatted_output.append("{'" + bank_name + "', " + str(bank_code) + "}")

result = ', '.join(formatted_output)

# Write the result to a file
with open('therapist.txt', 'w') as file:
    file.write(result)

print("Result has been written to therapist.txt")