data = [{'Absa Bank Kenya Plc', 3}, {'Absa Bank Kenya Plc', 3}, {'Access Bank Kenya', 26}, {'Access Bank Kenya', 26}, {'African BankingCorporation Ltd', 35}, {'African BankingCorporation Ltd', 35}, {'Bank of Africa Kenya Ltd', 19}, {'Bank of Africa Kenya Ltd', 19}, {'Bank of Baroda Kenya Limited', 6}, {'Bank of Baroda Kenya Limited', 6}, {'Bank of India', 5}, {'Bank of India', 5}, {'Caritas Microfinance Bank', 48}, {'Caritas Microfinance Bank', 48}, {'Central Bank of Kenya', 9}, {'Central Bank of Kenya', 9}, {'Choice Microfinance Bank', 36}, {'Choice Microfinance Bank', 36}, {'Citibank NA ', 16}, {'Citibank NA ', 16}, {'Co-operative Bank of Kenya Ltd', 11}, {'Co-operative Bank of Kenya Ltd', 11}, {'Consolidated Bank of Kenya Ltd', 23}, {'Consolidated Bank of Kenya Ltd', 23}, {'Credit Bank Limited', 25}, {'Credit Bank Limited', 25}, {'Development Bank of Kenya Ltd', 59}, {'Development Bank of Kenya Ltd', 59}, {'Diamond Trust Bank Ltd', 63}, {'Diamond Trust Bank Ltd', 63}, {'Dubai Islamic Bank Ltd', 75}, {'Dubai Islamic Bank Ltd', 75}, {'Ecobank Kenya Limited', 43}, {'Ecobank Kenya Limited', 43}, {'Equity Bank ltd', 68}, {'Equity Bank ltd', 68}, {'Family Bank Ltd', 70}, {'Family Bank Ltd', 70}, {'Faulu Microfinance Bank', 79}, {'Faulu Microfinance Bank', 79}, {'Guaranty Trust Bank Kenya', 53}, {'Guaranty Trust Bank Kenya', 53}, {'Guardian Bank Ltd', 55}, {'Guardian Bank Ltd', 55}, {'Gulf African Bank Ltd', 72}, {'Gulf African Bank Ltd', 72}, {'Habib Bank Limited', 8}, {'Habib Bank Limited', 8}, {'Housing Finance Corporation (HFC Bank)', 61}, {'Housing Finance Corporation (HFC Bank)', 61}, {'I & M Bank Ltd', 57}, {'I & M Bank Ltd', 57}, {'Jamii Bora Bank Ltd', 51}, {'Jamii Bora Bank Ltd', 51}, {'Kenya Commercial Bank Limited', 1}, {'Kenya Commercial Bank Limited', 1}, {'Kenya Women Microfinance Bank', 78}, {'Kenya Women Microfinance Bank', 78}, {'Kingdom Bank', 51}, {'Kingdom Bank', 51}, {'M-Oriental Bank Ltd', 14}, {'M-Oriental Bank Ltd', 14}, {'Mayfair Bank', 65}, {'Mayfair Bank', 65}, {'Middle East Bank Kenya Ltd', 18}, {'Middle East Bank Kenya Ltd', 18}, {'National Bank of Kenya Ltd', 12}, {'National Bank of Kenya Ltd', 12}, {'NCBA Bank Kenya', 7}, {'NCBA Bank Kenya', 7}, {'Paramount Universal Bank Ltd', 50}, {'Paramount Universal Bank Ltd', 50}, {'PostBank Kenya', 62}, {'PostBank Kenya', 62}, {'Premier Bank Kenya', 74}, {'Premier Bank Kenya', 74}, {'Prime Bank Limited', 10}, {'Prime Bank Limited', 10}, {'SBM Bank Kenya', 30}, {'SBM Bank Kenya', 30}, {'Sidian Bank Kenya', 66}, {'Sidian Bank Kenya', 66}, {'Spire Bank Kenya', 49}, {'Spire Bank Kenya', 49}, {'Stanbic Bank Kenya Limited', 31}, {'Stanbic Bank Kenya Limited', 31}, {'Standard Chartered Bank Kenya', 2}, {'Standard Chartered Bank Kenya', 2}, {'Stima Sacco', 89}, {'Stima Sacco', 89}, {'UBA Kenya Bank Ltd', 76}, {'UBA Kenya Bank Ltd', 76}, {'Victoria Commercial Bank Ltd', 54}, {'Victoria Commercial Bank Ltd', 54}]

# Remove duplicates using a set to keep track of unique entries
unique_data = []
seen = set()
for d in data:
    if tuple(d.items()) not in seen:
        unique_data.append(d)
        seen.add(tuple(d.items()))

print(unique_data)